
# GENERIC CONFIGURATION
export BENCHSUITE=selected_qualcom
export CHAMPSIM_BIN=champsim_ilru

# EXTRA EXPERIMENT SETTINGS
export REPL_IDP_VICTIM_THRESHOLD=2

# EXPERIMENT DESCRIPTOR TAG 
export DESCR_TAG="_ilru_a12_v${REPL_IDP_VICTIM_THRESHOLD}"

