# GENERIC CONFIGURATION
EXP_NAME=""
BENCHSUITES="spec"

# ITP settings
export ITP_INSTR_POS=0
export ITP_DATA_POS=2
export ITP_MAX_LRU=12
# PTP
export TLB_STRESS_THRESHOLD=10
export PTE_EVICTION_RATIO=1
# XPTP
export MIN_EVICTION_POSITION_L1D=8
export MIN_EVICTION_POSITION_L2C=4


### CONFIGURATION SPACE EXPLORATION ###
BASE_CONFIGURATIONS="dev_l2c-tdrrip_llc-tship"

declare -A CONFIGURATIONS=( 
	['ITP_INSTR_POS']="0"
	['ITP_DATA_POS']="2"
	['ITP_MAX_LRU']="12"
	['MIN_EVICTION_POSITION_L1D']="8" 
	['MIN_EVICTION_POSITION_L2C']="4" 
	['TLB_STRESS_THRESHOLD']="10" 
	['PTE_EVICTION_RATIO']="1" 
)

declare -a CONFIGURATION_TAGS=(
	dev_l2c-tdrrip_llc-tship
)


BUILD_CHAMPSIM=true

