
CLOUDSUITE="
cloud9_phase0_core0.trace.xz
cloud9_phase0_core1.trace.xz
cloud9_phase0_core2.trace.xz
cloud9_phase0_core3.trace.xz
cloud9_phase1_core0.trace.xz
cloud9_phase1_core1.trace.xz
cloud9_phase1_core2.trace.xz
cloud9_phase1_core3.trace.xz
cloud9_phase2_core0.trace.xz
cloud9_phase2_core1.trace.xz
cloud9_phase2_core2.trace.xz
cloud9_phase2_core3.trace.xz
cloud9_phase3_core0.trace.xz
cloud9_phase3_core1.trace.xz
cloud9_phase3_core2.trace.xz
cloud9_phase3_core3.trace.xz
cloud9_phase4_core0.trace.xz
cloud9_phase4_core1.trace.xz
cloud9_phase4_core2.trace.xz
cloud9_phase4_core3.trace.xz
cloud9_phase5_core0.trace.xz
cloud9_phase5_core1.trace.xz
cloud9_phase5_core2.trace.xz
cloud9_phase5_core3.trace.xz
"
CLOUDSUITE="
cassandra_phase0_core0.trace.xz
cassandra_phase0_core1.trace.xz
cassandra_phase0_core2.trace.xz
cassandra_phase0_core3.trace.xz
cassandra_phase1_core0.trace.xz
cassandra_phase1_core1.trace.xz
cassandra_phase1_core2.trace.xz
cassandra_phase1_core3.trace.xz
cassandra_phase2_core0.trace.xz
cassandra_phase2_core1.trace.xz
cassandra_phase2_core2.trace.xz
cassandra_phase2_core3.trace.xz
cassandra_phase3_core0.trace.xz
cassandra_phase3_core1.trace.xz
cassandra_phase3_core2.trace.xz
cassandra_phase3_core3.trace.xz
cassandra_phase4_core0.trace.xz
cassandra_phase4_core1.trace.xz
cassandra_phase4_core2.trace.xz
cassandra_phase4_core3.trace.xz
cassandra_phase5_core0.trace.xz
cassandra_phase5_core1.trace.xz
cassandra_phase5_core2.trace.xz
cassandra_phase5_core3.trace.xz
"

