
GAPP="
bc.kron-5154B.champsimtrace.xz
bc.twitter-1658B.champsimtrace.xz
bc.twitter-2320B.champsimtrace.xz
bc.twitter-309B.champsimtrace.xz
bc.twitter-876B.champsimtrace.xz
bc.web-1362B.champsimtrace.xz
bc.web-1627B.champsimtrace.xz
bc.web-2078B.champsimtrace.xz
bc.web-704B.champsimtrace.xz
bfs.kron-128B.champsimtrace.xz
bfs.kron-154B.champsimtrace.xz
bfs.kron-223B.champsimtrace.xz
bfs.kron-29B.champsimtrace.xz
bfs.kron-469B.champsimtrace.xz
bfs.kron-542B.champsimtrace.xz
bfs.twitter-10B.champsimtrace.xz
bfs.twitter-160B.champsimtrace.xz
bfs.twitter-163B.champsimtrace.xz
bfs.twitter-242B.champsimtrace.xz
bfs.twitter-303B.champsimtrace.xz
bfs.twitter-408B.champsimtrace.xz
bfs.twitter-44B.champsimtrace.xz
bfs.web-1066B.champsimtrace.xz
bfs.web-1306B.champsimtrace.xz
bfs.web-1825B.champsimtrace.xz
bfs.web-56B.champsimtrace.xz
bfs.web-79B.champsimtrace.xz
cc.kron-10B.champsimtrace.xz
cc.kron-135B.champsimtrace.xz
cc.kron-164B.champsimtrace.xz
cc.kron-17B.champsimtrace.xz
cc.kron-78B.champsimtrace.xz
cc.kron-82B.champsimtrace.xz
cc.kron-99B.champsimtrace.xz
cc.twitter-10B.champsimtrace.xz
cc.twitter-15B.champsimtrace.xz
cc.twitter-16B.champsimtrace.xz
cc.twitter-17B.champsimtrace.xz
cc.twitter-25B.champsimtrace.xz
cc.twitter-69B.champsimtrace.xz
cc.twitter-78B.champsimtrace.xz
cc.twitter-85B.champsimtrace.xz
cc.web-100B.champsimtrace.xz
cc.web-101B.champsimtrace.xz
cc.web-13B.champsimtrace.xz
cc.web-24B.champsimtrace.xz
cc.web-34B.champsimtrace.xz
cc.web-35B.champsimtrace.xz
cc.web-98B.champsimtrace.xz
cc.web-99B.champsimtrace.xz
pr.kron-349B.champsimtrace.xz
pr.kron-90B.champsimtrace.xz
pr.road-138B.champsimtrace.xz
pr.road-28B.champsimtrace.xz
pr.road-600B.champsimtrace.xz
pr.twitter-168B.champsimtrace.xz
pr.twitter-2161B.champsimtrace.xz
pr.twitter-2741B.champsimtrace.xz
pr.twitter-3197B.champsimtrace.xz
pr.twitter-833B.champsimtrace.xz
pr.web-16B.champsimtrace.xz
pr.web-3076B.champsimtrace.xz
pr.web-4993B.champsimtrace.xz
pr.web-709B.champsimtrace.xz
sssp.kron-2397B.champsimtrace.xz
sssp.kron-246B.champsimtrace.xz
sssp.road-151B.champsimtrace.xz
sssp.road-66B.champsimtrace.xz
sssp.twitter-1116B.champsimtrace.xz
sssp.twitter-2108B.champsimtrace.xz
sssp.twitter-792B.champsimtrace.xz
sssp.twitter-900B.champsimtrace.xz
sssp.web-1185B.champsimtrace.xz
tc.kron-1058B.champsimtrace.xz
tc.kron-2469B.champsimtrace.xz
tc.kron-4490B.champsimtrace.xz
tc.road-0B.champsimtrace.xz
tc.road-1B.champsimtrace.xz
tc.road-2B.champsimtrace.xz
tc.twitter-2097B.champsimtrace.xz
tc.twitter-34B.champsimtrace.xz
tc.twitter-4460B.champsimtrace.xz
tc.twitter-5663B.champsimtrace.xz
tc.web-2259B.champsimtrace.xz
tc.web-3876B.champsimtrace.xz
tc.web-5088B.champsimtrace.xz
"

GAP="
bc.kron-5154B.champsimtrace.xz
bc.twitter-1658B.champsimtrace.xz
bc.twitter-2320B.champsimtrace.xz
bc.twitter-309B.champsimtrace.xz
bc.twitter-876B.champsimtrace.xz
bc.web-1362B.champsimtrace.xz
bc.web-1627B.champsimtrace.xz
bc.web-2078B.champsimtrace.xz
bc.web-704B.champsimtrace.xz
bfs.kron-128B.champsimtrace.xz
bfs.kron-154B.champsimtrace.xz
bfs.kron-223B.champsimtrace.xz
bfs.kron-29B.champsimtrace.xz
bfs.kron-469B.champsimtrace.xz
bfs.kron-542B.champsimtrace.xz
bfs.twitter-10B.champsimtrace.xz
bfs.twitter-160B.champsimtrace.xz
bfs.twitter-163B.champsimtrace.xz
bfs.twitter-242B.champsimtrace.xz
bfs.twitter-303B.champsimtrace.xz
bfs.twitter-408B.champsimtrace.xz
bfs.twitter-44B.champsimtrace.xz
bfs.web-1066B.champsimtrace.xz
bfs.web-1306B.champsimtrace.xz
bfs.web-1825B.champsimtrace.xz
bfs.web-56B.champsimtrace.xz
bfs.web-79B.champsimtrace.xz
cc.kron-10B.champsimtrace.xz
cc.kron-135B.champsimtrace.xz
cc.kron-164B.champsimtrace.xz
cc.kron-17B.champsimtrace.xz
cc.kron-78B.champsimtrace.xz
cc.kron-82B.champsimtrace.xz
cc.kron-99B.champsimtrace.xz
cc.twitter-10B.champsimtrace.xz
cc.twitter-15B.champsimtrace.xz
cc.twitter-16B.champsimtrace.xz
cc.twitter-17B.champsimtrace.xz
cc.twitter-25B.champsimtrace.xz
cc.twitter-69B.champsimtrace.xz
cc.twitter-78B.champsimtrace.xz
cc.twitter-85B.champsimtrace.xz
cc.web-100B.champsimtrace.xz
cc.web-101B.champsimtrace.xz
cc.web-13B.champsimtrace.xz
cc.web-24B.champsimtrace.xz
cc.web-34B.champsimtrace.xz
cc.web-35B.champsimtrace.xz
cc.web-98B.champsimtrace.xz
cc.web-99B.champsimtrace.xz
pr.kron-349B.champsimtrace.xz
pr.kron-90B.champsimtrace.xz
pr.twitter-168B.champsimtrace.xz
pr.twitter-2161B.champsimtrace.xz
pr.twitter-2741B.champsimtrace.xz
pr.twitter-3197B.champsimtrace.xz
pr.twitter-833B.champsimtrace.xz
pr.web-16B.champsimtrace.xz
pr.web-3076B.champsimtrace.xz
pr.web-4993B.champsimtrace.xz
pr.web-709B.champsimtrace.xz
tc.kron-1058B.champsimtrace.xz
tc.kron-2469B.champsimtrace.xz
tc.kron-4490B.champsimtrace.xz
tc.road-0B.champsimtrace.xz
tc.road-1B.champsimtrace.xz
tc.road-2B.champsimtrace.xz
tc.twitter-2097B.champsimtrace.xz
tc.twitter-34B.champsimtrace.xz
tc.twitter-4460B.champsimtrace.xz
tc.twitter-5663B.champsimtrace.xz
tc.web-2259B.champsimtrace.xz
tc.web-3876B.champsimtrace.xz
tc.web-5088B.champsimtrace.xz
sssp.kron-2397B.champsimtrace.xz
sssp.kron-246B.champsimtrace.xz
sssp.twitter-1116B.champsimtrace.xz
sssp.twitter-2108B.champsimtrace.xz
sssp.twitter-792B.champsimtrace.xz
sssp.twitter-900B.champsimtrace.xz
sssp.web-1185B.champsimtrace.xz
tc.kron-1058B.champsimtrace.xz
tc.kron-2469B.champsimtrace.xz
tc.kron-4490B.champsimtrace.xz
tc.twitter-2097B.champsimtrace.xz
tc.twitter-34B.champsimtrace.xz
tc.twitter-4460B.champsimtrace.xz
tc.twitter-5663B.champsimtrace.xz
tc.web-2259B.champsimtrace.xz
tc.web-3876B.champsimtrace.xz
tc.web-5088B.champsimtrace.xz
"

SELECTED_GAPP="
bc.kron-5154B.champsimtrace.xz
bc.twitter-1658B.champsimtrace.xz
bc.twitter-2320B.champsimtrace.xz
bc.twitter-309B.champsimtrace.xz
bc.twitter-876B.champsimtrace.xz
cc.kron-10B.champsimtrace.xz
cc.kron-135B.champsimtrace.xz
cc.kron-164B.champsimtrace.xz
cc.kron-17B.champsimtrace.xz
cc.kron-78B.champsimtrace.xz
cc.kron-82B.champsimtrace.xz
cc.kron-99B.champsimtrace.xz
cc.twitter-10B.champsimtrace.xz
cc.twitter-15B.champsimtrace.xz
cc.twitter-16B.champsimtrace.xz
cc.twitter-17B.champsimtrace.xz
cc.twitter-25B.champsimtrace.xz
cc.twitter-69B.champsimtrace.xz
cc.twitter-78B.champsimtrace.xz
cc.twitter-85B.champsimtrace.xz
pr.kron-349B.champsimtrace.xz
pr.kron-90B.champsimtrace.xz
pr.twitter-168B.champsimtrace.xz
pr.twitter-2161B.champsimtrace.xz
pr.twitter-2741B.champsimtrace.xz
pr.twitter-3197B.champsimtrace.xz
pr.twitter-833B.champsimtrace.xz
sssp.kron-2397B.champsimtrace.xz
sssp.kron-246B.champsimtrace.xz
sssp.twitter-1116B.champsimtrace.xz
sssp.twitter-2108B.champsimtrace.xz
sssp.twitter-792B.champsimtrace.xz
sssp.twitter-900B.champsimtrace.xz
"

GAPS_CC_BC="
bc.kron-5154B.champsimtrace.xz
bc.twitter-1658B.champsimtrace.xz
bc.twitter-2320B.champsimtrace.xz
bc.twitter-309B.champsimtrace.xz
bc.twitter-876B.champsimtrace.xz
cc.kron-10B.champsimtrace.xz
cc.kron-135B.champsimtrace.xz
cc.kron-164B.champsimtrace.xz
cc.kron-17B.champsimtrace.xz
cc.kron-78B.champsimtrace.xz
cc.kron-82B.champsimtrace.xz
cc.kron-99B.champsimtrace.xz
cc.twitter-10B.champsimtrace.xz
cc.twitter-15B.champsimtrace.xz
cc.twitter-16B.champsimtrace.xz
cc.twitter-17B.champsimtrace.xz
cc.twitter-25B.champsimtrace.xz
cc.twitter-69B.champsimtrace.xz
cc.twitter-78B.champsimtrace.xz
cc.twitter-85B.champsimtrace.xz
"



#SELECTED_GAPS="
#bc.kron-5154B.champsimtrace.xz
#bc.twitter-1658B.champsimtrace.xz
#bc.twitter-2320B.champsimtrace.xz
#bc.twitter-309B.champsimtrace.xz
#bc.twitter-876B.champsimtrace.xz
#cc.kron-10B.champsimtrace.xz
#cc.kron-135B.champsimtrace.xz
#cc.kron-164B.champsimtrace.xz
#cc.kron-17B.champsimtrace.xz
#cc.kron-78B.champsimtrace.xz
#cc.kron-82B.champsimtrace.xz
#cc.kron-99B.champsimtrace.xz
#cc.twitter-10B.champsimtrace.xz
#cc.twitter-15B.champsimtrace.xz
#cc.twitter-16B.champsimtrace.xz
#cc.twitter-17B.champsimtrace.xz
#cc.twitter-25B.champsimtrace.xz
#cc.twitter-69B.champsimtrace.xz
#cc.twitter-78B.champsimtrace.xz
#cc.twitter-85B.champsimtrace.xz
#sssp.kron-2397B.champsimtrace.xz
#sssp.kron-246B.champsimtrace.xz
#sssp.twitter-1116B.champsimtrace.xz
#sssp.twitter-2108B.champsimtrace.xz
#sssp.twitter-792B.champsimtrace.xz
#sssp.twitter-900B.champsimtrace.xz
#sssp.web-1185B.champsimtrace.xz
#"

